### PR TITLE
Cn imageupload

### PR DESCRIPTION
**Pull request by CoopNich**
You'll need to install Pillow for this

`pip install Pillow`

Then make migrations to update your models
```
python manage.py makemigrations
python manage.py migrate
```
Test that you can add an image when uploading a product.  it should go to a media/bangazonllc_images folder in your root directory. It should create itself for you when you add your first image.

### CODE REVIEW

**Review by kwohl — APPROVED** [review]
This is amazing. Fantastic work.

To other reviewers: I recommend restarting your server after installing Pillow to avoid errors.

**Comment by kwohl** [comment]
Do we need to add media files to our .gitignore? @CoopNich

**Review by castlesmadeofcode — APPROVED** [review]
AMAZZZZZING

**Review by mKroogz — APPROVED** [review]
Works amazing thank you for working so hard on this :O

**Pull request merged**
