### PR TITLE
fixed null bug in product creation

### LINKED ISSUE #29: Product listing can be restocked
**Given** a user needs to sell more of an existing product
**When** the user is viewing the details for that product
**Then** a hyperlink should appear next to the quantity remaining field labeled "Update"

**Given** user is viewing the details of a product s/he is selling
**When** the "Update" hyperlink is clicked
**Then** the user is able to update the quantity of the product

### PR DESCRIPTION
**Pull request by CoopNich**
closes #29

git fetch --all

git checkout cn-quantityUpdate

Summary of this pull request:
Each user can update the quantity of only the products they have listed.

List of specifics:

-product.py refactored to always post NULL to images and location if "null" string is a value in the form data

To test:

View products being sold by the user currently logged in. Make sure there is a functional update button. Check for successful updates in the database
View products being sold by other users. Make sure there is no update button.

Make sure that if no local delivery is specified when creating a product and/or no image is uploaded, the final value of "location" and "image" for that product in the database is NULL

### CODE REVIEW

**Review by MReeds — APPROVED** [review]
Works great, Coop!

**Review by castlesmadeofcode — APPROVED** [review]
noice

**Review by mKroogz — APPROVED** [review]
I love this backend fix.  Really cool way to get around the formdata for image processing

**Review by kwohl — APPROVED** [review]
NICE

**Pull request merged**
